# Environment without gui-part


name: rostok_no_gui
channels:
  - https://conda.anaconda.org/intel
  - https://conda.anaconda.org/conda-forge
  - projectchrono
  - defaults
dependencies:
  - python=3.9.12
  - irrlicht==1.8.5
  - numpy
  
  - pip:
    - networkx==2.8.6
    - matplotlib==3.6.0
    - scipy
    - mcts==1.0.4
    - pytest
