# Environment without gui-part


name: rostok_no_gui
channels:
  - https://conda.anaconda.org/intel
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python=3.9.16
  - conda-forge::irrlicht=1.8.5
  - conda-forge::pythonocc-core=7.4.1
  - numpy
  - pip
  - pip:
    - networkx==2.8.6
    - matplotlib==3.6.0
    - scipy
    - mcts==1.0.4
    - pytest
    - open3d
