name: rostok
channels:
  - intel
  - conda-forge
dependencies:
  - python=3.10.8
  - projectchrono::pychrono=8.*
  - irrlicht=1.8.5
  - numpy
  - yapf
  - mypy
  - pylint
  - tk
  - pygraphviz
  - pip
  - pip:
    - networkx==2.8.6
    - matplotlib==3.6.0
    - scipy
    - mcts==1.0.4
    - pytest
    - open3d
