title: Rostok Documentation
#theme: jekyll-theme-minimal
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
markdown: kramdown
description: Bookmark this to keep an eye on my project updates!
  <div class='menu-group'>
    <div class='main-menu-item'><a href="index">About the library</a></div>
    <div class='menu-item'><a href="project_structure">Project structure</a></div>
    <div class='menu-item'><a href="Algorithm">Algorithms</a></div>
    <div class='menu-item'><a href="api">API documentation</a></div>
    <div class='menu-item'><a href="how_to_use">How to use our framework</a></div>
    <div class='menu-item'><a href="tutorials">Tutorials and documentation</a></div>
    <div class='menu-item'><a href="installation">Installation</a></div>
    <div class='menu-item'><a href="publications">Publications</a></div>
    <div class='menu-item'><a href="contacts">Contact us</a></div>
  </div>
show_excerpts: true