title: Rostok Documentation
theme: jekyll-theme-minimal
markdown: kramdown
description: Bookmark this to keep an eye on my project updates!
  <div class='menu-group'>
    <div class='main-menu-item'><a href="index">About the library</a></div>
    <div class='menu-item'><a href="project_structure">Project structure</a></div>
    <div class='menu-item'><a href="Algorithm">Algorithms</a></div>
    <div class='menu-item'><a href="how_to_use">How to use our framework</a></div>
    <div class='menu-item'><a href="installation">Installation</a></div>
    <div class='menu-item'><a href="publications">Publications</a></div>
    <div class='menu-item'><a href="contacts">Contact us</a></div>
  </div>
show_excerpts: true