name: Python Package using Conda



on: [ push ]


# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.12
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    
    - name: Install package for render
      run: |
        sudo apt-get install -y ffmpeg libsm6 libxext6 
    
    - name: Update conda
      run: |
        conda update -n base -c defaults conda

    - name: Install dependencies
      run: |
        conda env update --file environment_copy.yml --name base

    - name: Install Rostok
      run: |
        pip3 install -e .   

    - name: Test with pytest
      run: |
        pytest tests/test_simstep.py
