name: Python Package using Conda

on: [ push ]

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
  
    
    - name: Update conda
      run: |
        conda update -n base -c defaults conda

    - name: Install dependencies
      run: |
        conda env update --file environment_no_gui.yml --name base

    - name: Install Rostok
      run: |
        pip3 install -e . 
        
    - name: Test with pytest
      run: |
        pytest tests/test_graph.py 
